language: ruby
dist: trusty
sudo: false
rvm:
- 2.5.3
before_install:
- gem install bundler -v 2.0.1
script: bundle exec rake
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: rubygems
  api_key:
    secure: EXlBYrzl/hO8Jbe6gZ9iGSaNg+PX9R8IrzyBZqO15Ohl/cfOBpAH57Z7lg/ld+AMkBDZn/28rwRdyaQryiIimWLJko1dKOc5gGQIHePz5fIU/4KnEvZL7OQwyzbXKZIyZ/DRva3UjA+noX83G4cRtEQf9/nLHpkhmq1SeJcgGFC4rgtJ6N7k/CVCM86GW7R/nFn19IQY3L3kvfValSjysFN4NLh3l8CfWAFs9SfHKXerHRqeh9MjWkOuJTh+59rWembZ6N1MSbGJ6R3j1bvyudnbpoKyOonkxOiDIZT+cxwos/NHUcR2vgFJSy7xv8abYVOD+e1+bIO5egIKfyf9pGjbC7WuSmU4vHd49Rqyf9/bc8YD9nHliPR8psJDppR/3Z/6x99qQUfAEgb/GvVRH8Iy930z2plLfjtowlx6H4ef+j88xL0tXc8+6D0j9S8NSTQbDILS9VNv5oZoqP8FsVTdRK0rXesZMaPUBRiFdEKtaIZ2dWwnUtVSDNk8n+cFk+GF0FypPMIR3qYkszm0hXKslx894etKtbHG2g9KNP0g0f+W/h+Og9SfZJG0QNmUru2ujEa4sKcs/0zzSv8YN7EG/Bl/4Mi7mDoA5ouhd59ambGdZBVA7DR1kifkBcbXBUUjEHxoMIPRGlC6QuXg80rnVN/Sg7vcdUtgR13e1PE=
  gem: delivery-sdk-ruby
  on:
    tags: true
    repo: Kentico/delivery-sdk-ruby
