language: ruby
dist: trusty
sudo: false
rvm:
- 2.5.3
before_install:
- gem install bundler -v 2.0.1
script: bundle exec rake
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: rubygems
  api_key:
    secure: pjEn9URI4sStfFAOV70iqQIorvR4lTIduWjW+FfprQOAQDpPep7Bw6q4b7KTIM8mZiG+xvNavE+xcouRBKEv3/4mUuGfyxguNN3/DYU39GfqKon4XPkHE1Pf8trRcyrRG5G4YLOgQeqLK7JaVHlRD5IyUFU5wnppMI3cGYTRAD41tHAtkdRn8wSFcMl4a6Jfkkeup8yzhvFAPi5RLID9u1s6iG6MJeIa3/oPDO17sgYJKvwvNoTlS+3G/pMQYmJVxJL7kGyiCHHrZeE5M34XCth79G3e1k+vxHI1qmQsUoZITWg+/SPP4lQdwQNzAeUuCqRKWeOs0+mZmdBo2fhl56OuGlkEHkABMMQ/NKwr8riCE1dinlniTW57M49GJ4ob61/1ktgl2TUBGMxWt8wzXWHkuaSQZcuwJdCR8EyiFsvxTUQ1+HjjLFGZ9Gs6Zz1e+EXl390KpxcHmpLFaBzFvZtCPnAHM86rn5RddUJx7sD+y4DlahTdpkYY5edXBBE+feKixCJOVn7WcU59/XdIMpi3WcPOMEsp0zymaZgfOtg1V6k1FHKMq9N0Q2peYl5nwEJu2MCB3RcJpllBk3pIUbzMIvVNlWFglVbQ0wv8044zQ/zKXNtvlWJxU6gZGoFmC+EzSEpXgn9VonsswOXmVpUW3JMJbehfT7OaadAc584=
  gem: delivery-sdk-ruby
  on:
    tags: true
    repo: Kentico/delivery-sdk-ruby
