language: ruby
dist: trusty
sudo: false
rvm:
  - 2.5.3
before_install: 
  - gem install bundler -v 2.0.1
  - apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
  - bundle config --local build.nokogiri "--use-system-libraries"
script: bundle exec rake
