language: ruby
dist: trusty
sudo: false
rvm:
- 2.5.3
before_install:
- gem install bundler -v 2.0.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  - CC_TEST_REPORTER_ID=2f8aa9afa164aac0c5e373596a5576be18085cea9f7cecfdafe02065f706eb88 TEST=1 TEST_SECURE_API_ENABLED=true PROJECT_ID=faf446d2-0544-0039-bb43-5d6ef816661a PREVIEW_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4NmY3MDQ2Y2U4YWI0ZjY4OWRjNDdjZmNiOWNjZWVmYyIsImlhdCI6IjE1NTIwMzg3NjYiLCJleHAiOiIxODk3NjM4NzY2IiwicHJvamVjdF9pZCI6ImZhZjQ0NmQyMDU0NDAwMzliYjQzNWQ2ZWY4MTY2NjFhIiwidmVyIjoiMS4wLjAiLCJhdWQiOiJwcmV2aWV3LmRlbGl2ZXIua2VudGljb2Nsb3VkLmNvbSJ9.NpFvn45TfhlRhtOmexEAD0rRa-mnc1XA0ltU62EDPtE SECURE_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwNzI0NzQ4NDQ5ZDY0OGUwOTFiMzgzZjJjY2JlOTViZCIsImlhdCI6IjE1NTIwMzg3ODUiLCJleHAiOiIxODk3NjM4Nzg1IiwicHJvamVjdF9pZCI6ImZhZjQ0NmQyMDU0NDAwMzliYjQzNWQ2ZWY4MTY2NjFhIiwidmVyIjoiMS4wLjAiLCJhdWQiOiJkZWxpdmVyLmtlbnRpY29jbG91ZC5jb20ifQ.qZ2W4VojrwFaApajkyesUy4aNcG8OUu6C2ZlF84aL0M
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: rubygems
  api_key:
    secure: eoEZvYiWlruYyG1lHjpLmjhPNbn0o4a0xnYbIltEIvna11Bc3A0pNlnjzzxINTZEPgLRnhpwSQnxeqwH0pbgTtxf2fg6NFscBHSiw2Y/wtDl1q/3nyyynwtG19RAL6dbLGj5djSAYnuKb/LXNGWnlPfIJER42DHeiMB6sLKRoj+6KztNaYb96NRf0KvMae0fqGAdFera+Ppzbe5kmtu74luXVQXdqYHIdWoPKTdI3vw7ooOpIm0vSoHspp2yMjWs4vP8pfZbmoqcUOt1TWZvu9Mq1eXNNj6J6IWurErgz4euNylplBJgRu/HId7Im1v6hE0PF/GdTHHkhiU8vUwbCgySegm0f/81bOdGD0VI0n70tPJTApv9dBAi1jKLVX2LNPKdR56WzTPM+5i/BFCggp2GC4X48fuM2kHPtBP63Q0tt0fN0UorPKq48ltFQRIbo2WZOYlCnoMuneUIuvhkUl8OPyOvZCvfDuVxi2CTydP3SWzf5dLouDZAa79J3vytbiFZbQ19lK3o/l7CONkKvBfn3MhUb+z/9pvnl50P7MDQSnkzjPORQUkY0xSV1mCJq+CrlNSy7PEJErCjkcpM6vTnFDfvg9jRAv7ZP5/cgDY4n8H09iOV+1kVK2/jRaqbWD4aNi2/Cl90gmb+e6sJwTy/IEusiBV5NrETqFWYjUA=
  gem: delivery-sdk-ruby
  on:
    tags: true
    repo: Kentico/kontent-delivery-sdk-ruby
